# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91f321578b1ceeded5495ca4e279a82da2fa0be82f4764fa7aabdff06100193c26bbc980acb04a16e72ce511018cb051ae210d15ef7d84087bc87360d297101e

test:
  secret_key_base: ff5b121ec9f6eed7bb1f82e691f59f34f3f15fb8574af2faac5abab0a972fbb77c19e1e25494b24fb8f75547f7bf7f327b1465cf894a4cb5717836cad627ad94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
